on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
<<<<<<< Updated upstream
        uses: TBD-salt-23/github-pages-deploy-action@v4
=======
        uses: tbd-spa2/github-pages-deploy-action@v4
>>>>>>> Stashed changes
        with:
          folder: dist
