name: GitHub Classroom Workflow

on:
  push:
    branches:
      - dev

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: education/autograding@v1
