name: TBD Test Suite

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clean install and unit tests
        run: |
          npm ci
          npm run t
          npm run lint -- --fix

      - name: Run server & e2e if pull request
        if: github.event_name == 'pull_request'
        run: |
          npm audit
          npm run dev &
          sleep 5
          npm run cypress
