name: GitHub Classroom Workflow

on:
  pull_request:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm audit
      - run: npm run dev &
      - run: sleep 5
      - uses: education/autograting_pull@v1
