name: TBD Test Suite

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clean install and unit tests and linting
        run: |
          npm ci
          npm t
          npm run lint

      - name: Run server & e2e if pull request
        if: github.event_name == 'pull_request'
        run: |
          npm audit
          npm run dev &
          npm run cypress
