name: GitHub Classroom Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Run audit if pull request
        if: github.event_name == 'pull_request'
        run: npm audit

      - name: Run server if pull request
        if: github.event_name == 'pull_request'
        run: npm run dev &
      - run: sleep 5
